name: mosim_modloader
description: "The Reactor Modloader for the game MoSim, made in Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

#dart run msix:create
msix_config:
  display_name: Reactor Modloader
  publisher_display_name: Jedi_4  
  identity_name: CCShambots.ReactorModloader
  store: true
  publisher: CN=A3792B11-8FEE-477E-B2FF-B9039EB1B82B
  capabilities: internetClient, location, microphone, webcam
  logo_path: C:\Users\barta\Documents\GitHub\mosim_modloader\assets\icon\icon.png

dependencies:
  archive: ^3.6.1
  dio: ^5.6.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter

  intl: ^0.19.0
  open_filex: ^4.5.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  simple_icons: ^10.1.3
  toastification: ^2.1.0
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.7
  flutter_launcher_icons: ^0.13.1


# Run `flutter pub run flutter_launcher_icons`
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon-512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon-512.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon-512.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon-512.png"

flutter:
  uses-material-design: true
